# Use an official Python runtime as a parent image
FROM python:3.11

# Install netcat-openbsd
RUN apt-get update && apt-get install -y netcat-openbsd

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /code/